apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: 057096910794.dkr.ecr.us-east-1.amazonaws.com/flag-service:938ff08
          ports:
            - containerPort: 8002
