auth-service:
    secrets:
        MASTER_KEY: ENC[AES256_GCM,data:z9YBx+lQHJiuoUocBzxHAz4=,iv:IRVN0CJcKlKEvPUroHNLokVg8zUUAkoQ01ji1LxemuU=,tag:hU9Je12knqLKZNpJYpJt2Q==,type:str]
        POSTGRES_DB: ENC[AES256_GCM,data:Waqvr6iTOQ==,iv:naCeDE33uXG7rYkfB29bb4w+0gIAeKnS9gknvlrYMdE=,tag:hOpq+8yIfH38BeVtaYI55w==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:oqPbLWiwRLb+ipbe,iv:nKhtUnsBxetBTu5tA31UVJtRYB2mXI1CxDaIVJuF/5w=,tag:+MUPZBVdaU5qvCYE9RtFtA==,type:str]
        POSTGRES_PORT: ENC[AES256_GCM,data:ojzGyw==,iv:UzdiEtQS3cdW0FHm0lfdf9sU9iMo0rYa8Uik1BRjIr0=,tag:fZF6p7VRTanfRqT83LY9BA==,type:int]
        POSTGRES_USER: ENC[AES256_GCM,data:p6nYi1PW2AyxYOAX,iv:NKjujOonue/wXA9X4M/wFM839s2DTI39NZHPg/oe3cA=,tag:7fIOeL+FfWLYDcFjmC0aPg==,type:str]
flag-service:
    secrets:
        AUTH_SERVICE_URL: ENC[AES256_GCM,data:FjOLnUbVvlVknTd5zuE8y1DVcjgf/+4ov00knPSYlPZVR43d9sDwtKjviFpOZF/cRp01oYe/RxJYtWc=,iv:daKlNVJglIaLzuGpJy+t3mOKeC2aVmS29UARP1nck+M=,tag:e84AfC7YVxiF8pIpcLlbNA==,type:str]
        POSTGRES_DB: ENC[AES256_GCM,data:4QRauXRouA==,iv:REis/2a/0OMUdd01s/6H8y6zIufxTrICMgiS/3fQmLg=,tag:1IDZMwXHZoQ8paY1s+fvAg==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:bY2e7MlXU73/adxN,iv:2GfiZUHmZsW3fH3hujAc55CkH4q/MJJJHGwn98LjQeA=,tag:gFMMO8P3q9SG4t9YMOgyZw==,type:str]
        POSTGRES_PORT: ENC[AES256_GCM,data:p1J6HA==,iv:xlIepO5hZTAR7RQR1QUHjlddLMeM/qojBysazoPgYQE=,tag:U8UYjEgnnbkFZ8Pl3deSbQ==,type:int]
        POSTGRES_USER: ENC[AES256_GCM,data:Sdocya5fFbhC5u4y,iv:lZYHcJXEYmhjayZiABMf8XkGUnpQXLdKHR9oxVBWlLo=,tag:S26K09bs0+ACn+AAmenpGw==,type:str]
targeting-service:
    secrets:
        AUTH_SERVICE_URL: ENC[AES256_GCM,data:m/fIXJuGnnSSqMYoA7BAmd7FE+09Jm698tJYSIddl1t/w+WjyheB7RZWtBvRcIlQtDWbxYKGASCNS/g=,iv:3Owax2KQMUBLvh0sTK4IIZ6yhlG5R0xKGCao3AmBa9Y=,tag:KHCpxj+OyUB9IcC7wGY6CQ==,type:str]
        POSTGRES_DB: ENC[AES256_GCM,data:UGSzTOKseDad9iVn,iv:pKC4s6ny5W8ow+snTv4rlwNrNTJC9Q1/Qd3hw+FN6p8=,tag:k9bPnxcPeOJw+kI5W3/xbw==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:dbVCh0Miwf9pFsR6,iv:LcwifMyTdZyGncveRci/zZ6jfoXwqUFHVdn+i/X0hZM=,tag:H+0JwfrA/AbUGPLHq9kFgg==,type:str]
        POSTGRES_PORT: ENC[AES256_GCM,data:Nvtj5w==,iv:CBcz9YT8zxYOXSpYJi4FzmxrNmCbLLpQPD0W5IISNZA=,tag:QvwlT3sgpItXrnARTrMzmw==,type:int]
        POSTGRES_USER: ENC[AES256_GCM,data:8QOnbPH+MLF/go+3,iv:vDy4LD/hKs13unqaiUVyhHtdjrNmk+Ro5DJdu9qksi8=,tag:Qk+UwD+W2POXAqlzjSdSFQ==,type:str]
evaluation-service:
    secrets:
        FLAG_SERVICE_URL: ENC[AES256_GCM,data:tSYIcjmOVwXN5+dXRlE/8+gDh7/nrJVPyZGvMWJdy/1lB25XaqmqDRUjefCiKpAaikCxM1w/sRvcnxU=,iv:1Sy0axEb9k5H5I3EeK99ZlCTpKuZOvRjf95QLPLe7oQ=,tag:ZfpAsvhgnQSsShTDt2WAIA==,type:str]
        SERVICE_API_KEY: ENC[AES256_GCM,data:xPgcXaw=,iv:1UVTDJNxWYWQiisCItgQrf15enxO9s06EKYYmx6fMYE=,tag:IlFmnlkbqxd+hz0KJJF2fw==,type:str]
        TARGETING_SERVICE_URL: ENC[AES256_GCM,data:IG9Q26TjtCuY7SFzkXyl3gWe6CSTw9PyiAo0lf6sHRFZsLxmAMDOtQTsGhtjl74Vb46VrtEZiIVQBGA=,iv:8e0ANPYthI15adM9dnistnzbQZ2eU0iHn+CnqvSDLB8=,tag:cEsxc8Afco071Ad8dhqfcA==,type:str]
analytics-service:
    secrets:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hYli9Y9sGw1DLRAF9mLAwX0C2VU=,iv:X5f+kHQilq3qcng73YyolGXWzxjtii/HOXuIGeYKx7E=,tag:hLI8tDDGXlaVvZUyFeTX0g==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vt0Zaa63HrRuGXJWBbo7dMWQpRn1TETfW1FpksLEB9BJ8uyxFAm/Hw==,iv:3UW8Z9ia0+VOkAXznHN0bxknUENJnkcKRx5xTt/yCJo=,tag:mY+V8ii65ZkiZkwUSTTthA==,type:str]
        AWS_SESSION_TOKEN: ENC[AES256_GCM,data:Qr2L9opdjxZuyZBqu/k/Rw5fOz0iorR2kdIau//xvySI6xpZRGbr1DXn2AT/G7dn5hgR0KJFWqdnSzGCAES/U6NjUenVy5L7glH7n6IESkq0AKcHmQNA5uTxPDFn1Z6augpZClHrSJTucYBBVG6Sk/hZUcSayOCJr+FC4gNJgZIVGQrEgpa3MLEHf7n1GhOOvqx9tP4dAbnx2QECctlkEK5DQdYFEf1JTW219OoIfxAROeVRve4aCRGuqO7D/TVtK1++y15E8RndbgdW+y3kANQw0BeYMcOuZouxv8ETaDJNoAAWFCheiaXa6y3Fng3fUWIFtjqzyVdGS/zYXl/a6hFNRininVTe4WwJvMYtPLrxM73EOmhlNNiPBL96/xc7pInUmTBLc8dzyoZXoA2eP2O8yLZmFEN76rU4uNSoG1QY6cR+KfZoF5U5Ms4CYFAlxqLIPxA0Rry/Y7tnu3IooBXHWL65FYz58b10m3mv6QXadELkWdXhJ6+JdF3hMvy+nWV89pJPiGcCofMqnaCkb+CQlMZ2LDkxYAfCw9FM3ViQPcMJCRpvnTYJr3meDK/D1ExNe18cSMR2PWzSKjj1xHzdjo1kJ8KCSXuWJd31nJO/hsQcY/DMVpW1xr9MxV7IFhuQVd7LwIyL0NPUCv6h6DRqgpmSQ08my+EgTEDTfN4HSSeWVTInEoFFJyXOQBEzMDO+bD/bSr9JiRl2cRFjM9QMEDLy3J7HAji5JmlD0Vog1+TTqGHdhviQpBAXkOuq+4I4Ojl+/Z39ELI9WOjqjO50NGOYhgYxSYiA7xKv4E0rTM6gZHjwh6QdSZGJYDGz2TCA+Ckaa2Wjj/cc8ur8kZ36uimdWsqPFPosuwgMvERH+RzBP3ElYT7mTlcQY6iu9X3RlrzmrzCLp6BEL3WvYOJFYqopljEgzG3Gy7wds685g6m/u/WBo/rtaw/v2+skm58F1tDwWocYo53jQI9lQ6G+DIbCq02TFTF+FWiAlj41NvVl1tbUnTYYd5W7HmAsNDCKUxmjLPs=,iv:mV1wXBMI5uPEbGfac2ygEc+FLs/CRSBPyiWjy8yDvHI=,tag:2yAoKpZI1VLVl+a3LwMTNg==,type:str]
sops:
    age:
        - recipient: age1l52fgy7vnldsqdma7ghskhrjc6xeqm9a44qrucvdn09pm2c2h4ks2hg5qg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU0ZHWVpWd2pkbFBvS21C
            UkExbEZkTFo1ZXN2YkhSbFZWQlhscndYT0dVClk1eDY1OFdOd0RHcGhhNmlwcWg5
            Y0c2VXlydHltVWtpZEJBUDRJWTZIUDQKLS0tIFRmQzhYYTMyRzFHQ3lick93cDRo
            Z0R6RjZTdmpYU0V1NjkxUVdIVngvd2cKublPAGjerXm0b5+0GsHSzOYwixxPs3o2
            B6QXncXpBSJUJaE+r5zCNcccvzKoOD3PZh9plNPpxsxhaClBz1AD1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T23:05:24Z"
    mac: ENC[AES256_GCM,data:oz1GmWrDr6gnSlkhKxXItQn4RbRR2bddpzR1c/g71K25ITIHKj+H/dORCytTWyGqwyda0O5bSKnk0xAaJZlndNYWnyibAiZZGlgyM5e4WkkSMPZ92Kq6qgid2ZQFVw+4oU3lRV7iGUMHqcYp3lIhBkfDCfe0iZRmbRckgaVph2Y=,iv:BQzUFrOqcmiUeSyy4JTPI9dVf6mY3tZfeb7i0x8XjkY=,tag:U5Gp7Tx8mJSK9vU5/NYlOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
