auth-service:
  namespace: auth-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/auth-service:c0c5656
  port: 8001
  ingress: 
    path: /auth-service(/|$)(.*)

flag-service:
  namespace: flag-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/flag-service:a1a9a84
  port: 8002
  ingress: 
    path: /flag-service(/|$)(.*)
  


targeting-service:
  namespace: targeting-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/targeting-service:c05aa7a
  port: 8003
  ingress: 
    path: /targeting-service(/|$)(.*)


evaluation-service:
  namespace: evaluation-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:2fc0b5b
  port: 8004
  ingress: 
    path: /evaluation-service(/|$)(.*)

analytics-service:
  namespace: analytics-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/analytics-service:b45587c
  port: 8005
  ingress: 
    path: /analytics-service(/|$)(.*)
  hpa:
    name: analytics-hpa
    minReplicas:
    maxReplicas:
    targetCPU:

argocd:
  namespace: argocd
  port: 80
  ingress:
    path: /argocd(/|$)(.*)
