auth-service:
  namespace: auth-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 618678798048.dkr.ecr.us-east-1.amazonaws.com/auth-service:b3485b1
  port: 8001
  ingress: 
    path: /auth-service(/|$)(.*)

flag-service:
  namespace: flag-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/flag-service:35b6cbd
  port: 8002
  ingress: 
    path: /flag-service(/|$)(.*)
  


targeting-service:
  namespace: targeting-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/targeting-service:e0c0ac5
  port: 8003
  ingress: 
    path: /targeting-service(/|$)(.*)


evaluation-service:
  namespace: evaluation-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:e293cfc
  port: 8004
  ingress: 
    path: /evaluation-service(/|$)(.*)

analytics-service:
  namespace: analytics-service
  maxSurge: 50%
  maxUnavailable: 0
  replicas: 2
  image: 654654467270.dkr.ecr.us-east-1.amazonaws.com/analytics-service:d4f668e
  port: 8005
  ingress: 
    path: /analytics-service(/|$)(.*)
  hpa:
    name: analytics-hpa
    minReplicas:
    maxReplicas:
    targetCPU:

argocd:
  namespace: argocd
  port: 80
  ingress:
    path: /argocd(/|$)(.*)
