apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 618678798048.dkr.ecr.us-east-1.amazonaws.com/analytics-service:1515da2
          ports:
            - containerPort: 8005
