apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 057096910794.dkr.ecr.us-east-1.amazonaws.com/auth-service:0cd7203
          ports:
            - containerPort: 8001
