# Etapa 1: Build do Go
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copia arquivos de dependências
COPY go.mod go.sum ./
RUN go mod download

# Copia todo o código
COPY . .

# Compila o binário
RUN go build -o auth-service .

# Etapa 2: Container final mais leve
FROM alpine:3.23
RUN apk update && apk upgrade

WORKDIR /app

# Copia o binário e o .env
COPY --from=builder /app/auth-service .

EXPOSE 8001

# Comando padrão ao iniciar o container
CMD ["./auth-service"]
