{{- range $appName, $appConfig := .Values }}
{{- if and (kindIs "map" $appConfig) (hasKey $appConfig "secrets") }}
apiVersion: v1
data:
  {{- range $key, $value := $appConfig.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $appName }}-db-secret
  namespace: {{ default "default" $appConfig.namespace }}
type: Opaque
---
{{- end }}
{{- end }}