apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  description: Deploy ArgoCD
  sourceRepos:
    - https://github.com/toni182/TechChallenge3
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'