apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 618678798048.dkr.ecr.us-east-1.amazonaws.com/targeting-service:cf9dfd1
          ports:
            - containerPort: 8003
