name: CD to create ArgoCD manifests

on:
  workflow_call:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: techchallenge3-cluster

jobs:
  build-test-security:
    name: Build + Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
        run: |
          echo "kubectl version: $(kubectl version --client)"

      - name: Get EKS cluster info
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
          echo "current context: $(kubectl config current-context)"
          echo "current nodes: $(kubectl get nodes)"

      - name: apply ArgoCD
        run: |
          kubectl apply --server-side --force-conflicts -k base/
          kubectl wait --for=condition=Established crd/applications.argoproj.io --timeout=60s
          kubectl wait --for=condition=Established crd/appprojects.argoproj.io --timeout=60s
          kubectl wait --for=condition=Established crd/applicationsets.argoproj.io --timeout=60s
          kubectl apply --server-side --force-conflicts -k apps/

      - name: Verifying ArgoCD
        run: |
          echo "ArgoCD version: $(kubectl get deployment argocd-server -n argocd -o jsonpath='{.spec.template.spec.containers[0].image}')"

      - name: Restoring SealedSecret keys
        run: |
          echo "${{ secrets.SEALED_SECRETS_YAML }}" | base64 -d > sealed-secrets.yaml
          kubectl apply -f sealed-secrets.yaml

      - name: Verifying SealedSecret keys
        run: |
          kubectl get secrets -n sealed-secrets

      - name: Deploying SealedSecret
        run: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
          helm install sealed-secrets sealed-secrets/sealed-secrets -n sealed-secrets
