name: Deploy All Services

on:
  workflow_dispatch:

jobs:

  deploy-auth:
    uses: ./.github/workflows/auth.yml

  deploy-flag:
    uses: ./.github/workflows/flag.yml

  deploy-targeting:
    uses: ./.github/workflows/targeting.yml

  deploy-evaluation:
    uses: ./.github/workflows/evaluation.yml

  deploy-analytics:
    uses: ./.github/workflows/analytics.yml
